version: '2'

services:

  user-ms:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: user-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: user
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3000:3000"
    depends_on:
      - user-db

  user-db:
    build: ./db
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: user-db
    ports:
      - 3306:3306
    restart: on-failure
